version: '3'

services:
  beacons-scanner:
    build: .
    env_file:
      - env
    volumes:
      - ./_service_storage:/app/_service_storage
    expose:
      - "5000"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    