version: '3'

services:
  beacons-scanner:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - env
    volumes:
      - ./_service_storage:/app/_service_storage
    expose:
      - "5000"
    ports:
      - "5000:5000"
    network_mode: host
    